#!/usr/bin/env python3
# PS5VR
# Copyright (C) 2026 Husam Osman
# SPDX-License-Identifier: GPL-3.0-or-later
"""Writes the headset HDR video pipelines (engine/shaders/agc/vr_p010_*_ext.pipe).

The PS VR2 panel is HDR; Hmd2 takes each layer as SDR and scales it up
(lumaScaleFromSdrToHdr in its reprojection). These pipes keep an HDR
picture's light above SDR white instead of tone-mapping it away: P010 HDR10
(PQ) or HLG -> linear light, BT.2020 -> BT.709 primaries, 1.0 = SDR white
(203 nits), highlights above 1.0, stored with the same 2.2 gamma as SDR
pictures (extended past 1.0) into an RGBA16F surface. Experimental: whether
Hmd2 shows values above 1.0 brighter than white is what this tests.
Compile with build_agc_pipes.py (amdllpc, gfx1013).
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "engine", "shaders", "agc")

VS = r"""#version 450

layout(set = 0, binding = 0, std140) uniform VideoConstants {
    vec2 uCrop;
    vec2 uScale;
} video;

layout(location = 0) out vec2 vUV;

void main() {
    vec2 p = vec2(float(gl_VertexIndex & 1), float((gl_VertexIndex >> 1) & 1));
    vUV = vec2(p.x, 1.0 - p.y) * video.uCrop;
    gl_Position = vec4((p * 2.0 - 1.0) * video.uScale, 0.0, 1.0);
}
"""

COMMON = r"""#version 450

layout(set = 1, binding = 0) uniform sampler2D uY;
layout(set = 1, binding = 1) uniform sampler2D uUV;

layout(location = 0) in vec2 vUV;
layout(location = 0) out vec4 out_color;

vec3 yuv2020(float y, float U, float V) {
    float Yp = (y - 0.0627451) * 1.1640625;
    return vec3(Yp + 1.4746 * V,
                Yp - 0.16455 * U - 0.57135 * V,
                Yp + 1.8814 * U);
}

const float SDR_WHITE = 203.0;   /* BT.2408 graphics white, nits */

/* linear BT.2020 nits -> BT.709 relative to SDR white, extended 2.2 gamma */
vec4 out_ext(vec3 nits2020) {
    vec3 c = vec3(dot(nits2020, vec3( 1.6605, -0.5876, -0.0728)),
                  dot(nits2020, vec3(-0.1246,  1.1329, -0.0083)),
                  dot(nits2020, vec3(-0.0182, -0.1006,  1.1187)));
    c = max(c, vec3(0.0)) / SDR_WHITE;
    return vec4(pow(c, vec3(1.0 / 2.2)), 1.0);
}
"""

PQ_FS = COMMON + r"""
float pq_to_nits(float N) {
    float Np = pow(max(N, 0.0), 1.0 / 78.84375);
    return 10000.0 * pow(max(Np - 0.8359375, 0.0) / (18.8515625 - 18.6875 * Np),
                         1.0 / 0.1593017578125);
}

void main() {
    float y = texture(uY, vUV).r * 64.0615844;
    vec2 uv = texture(uUV, vUV).rg * 64.0615844 - vec2(0.5);
    vec3 e = clamp(yuv2020(y, uv.x, uv.y), 0.0, 1.0);
    out_color = out_ext(vec3(pq_to_nits(e.r), pq_to_nits(e.g), pq_to_nits(e.b)));
}
"""

HLG_FS = COMMON + r"""
float hlg_eotf(float e) {
    if (e <= 0.5)
        return (e * e) / 3.0;
    return (exp((e - 0.55991073) / 0.17883277) + 0.28466892) / 12.0;
}

/* scene light, BT.2100 OOTF for a 1000-nit display (system gamma 1.2) */
void main() {
    float y = texture(uY, vUV).r * 64.0615844;
    vec2 uv = texture(uUV, vUV).rg * 64.0615844 - vec2(0.5);
    vec3 e = clamp(yuv2020(y, uv.x, uv.y), 0.0, 1.0);
    vec3 scene = vec3(hlg_eotf(e.r), hlg_eotf(e.g), hlg_eotf(e.b));
    float ys = max(dot(scene, vec3(0.2627, 0.6780, 0.0593)), 1e-6);
    out_color = out_ext(1000.0 * pow(ys, 0.2) * scene);
}
"""


def resource_mapping(samplers):
    lines = [
        "userDataNode[0].visibility = 2",
        "userDataNode[0].type = DescriptorTableVaPtr",
        "userDataNode[0].offsetInDwords = 0",
        "userDataNode[0].sizeInDwords = 1",
        "userDataNode[0].next[0].type = DescriptorConstBuffer",
        "userDataNode[0].next[0].offsetInDwords = 0",
        "userDataNode[0].next[0].sizeInDwords = 4",
        "userDataNode[0].next[0].set = 0",
        "userDataNode[0].next[0].binding = 0",
        "userDataNode[1].visibility = 64",
        "userDataNode[1].type = DescriptorTableVaPtr",
        "userDataNode[1].offsetInDwords = 0",
        "userDataNode[1].sizeInDwords = 1",
    ]
    for i in range(samplers):
        lines += [
            f"userDataNode[1].next[{i}].type = DescriptorCombinedTexture",
            f"userDataNode[1].next[{i}].offsetInDwords = {i * 12}",
            f"userDataNode[1].next[{i}].sizeInDwords = 12",
            f"userDataNode[1].next[{i}].set = 1",
            f"userDataNode[1].next[{i}].binding = {i}",
        ]
    return "\n".join(lines)


def write_pipe(name, frag, comment):
    text = f"""; {name} - {comment}
; Generated by tools/shaders/gen_vr_hdr_pipes.py. Edit the generator, not this file.

[Version]
version = 65

[VsGlsl]
{VS}
[VsInfo]
entryPoint = main

[FsGlsl]
{frag}
[FsInfo]
entryPoint = main

[ResourceMapping]
{resource_mapping(2)}

[GraphicsPipelineState]
topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST
nggState.enableNgg = 1
nggState.enableGsUse = 0
colorBuffer[0].format = VK_FORMAT_R16G16B16A16_SFLOAT
colorBuffer[0].channelWriteMask = 15
colorBuffer[0].blendEnable = 0
"""
    with open(os.path.join(OUT, f"{name}.pipe"), "w", newline="\n") as f:
        f.write(text)
    print(f"  wrote {name}.pipe")


if __name__ == "__main__":
    write_pipe("vr_p010_pq_ext", PQ_FS, "P010 HDR10 -> extended-range BT.709 for the headset")
    write_pipe("vr_p010_hlg_ext", HLG_FS, "P010 HLG -> extended-range BT.709 for the headset")
