/* Fonts, icons and artwork from assets/ (paths relative to ps5vr-app/),
 * compiled into the eboot, so nothing depends on the app's file layout.
 * Generated by scripts/gen_assets.py. */
#include "ui_assets.h"

__asm__(".section .rodata\n.balign 16\n.global app_blob_font_inter_regular\napp_blob_font_inter_regular:\n.incbin \"assets/fonts/Inter-Regular.ttf\"\n.byte 0\n.global app_blob_font_inter_regular_end\napp_blob_font_inter_regular_end:\n.previous\n");
extern const uint8_t app_blob_font_inter_regular[], app_blob_font_inter_regular_end[];
ui_asset ui_asset_font_inter_regular(void)
{
    ui_asset a = {app_blob_font_inter_regular, (size_t)(app_blob_font_inter_regular_end - app_blob_font_inter_regular) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_font_inter_medium\napp_blob_font_inter_medium:\n.incbin \"assets/fonts/Inter-Medium.ttf\"\n.byte 0\n.global app_blob_font_inter_medium_end\napp_blob_font_inter_medium_end:\n.previous\n");
extern const uint8_t app_blob_font_inter_medium[], app_blob_font_inter_medium_end[];
ui_asset ui_asset_font_inter_medium(void)
{
    ui_asset a = {app_blob_font_inter_medium, (size_t)(app_blob_font_inter_medium_end - app_blob_font_inter_medium) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_font_inter_semibold\napp_blob_font_inter_semibold:\n.incbin \"assets/fonts/Inter-SemiBold.ttf\"\n.byte 0\n.global app_blob_font_inter_semibold_end\napp_blob_font_inter_semibold_end:\n.previous\n");
extern const uint8_t app_blob_font_inter_semibold[], app_blob_font_inter_semibold_end[];
ui_asset ui_asset_font_inter_semibold(void)
{
    ui_asset a = {app_blob_font_inter_semibold, (size_t)(app_blob_font_inter_semibold_end - app_blob_font_inter_semibold) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_font_inter_bold\napp_blob_font_inter_bold:\n.incbin \"assets/fonts/Inter-Bold.ttf\"\n.byte 0\n.global app_blob_font_inter_bold_end\napp_blob_font_inter_bold_end:\n.previous\n");
extern const uint8_t app_blob_font_inter_bold[], app_blob_font_inter_bold_end[];
ui_asset ui_asset_font_inter_bold(void)
{
    ui_asset a = {app_blob_font_inter_bold, (size_t)(app_blob_font_inter_bold_end - app_blob_font_inter_bold) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_font_roboto_regular\napp_blob_font_roboto_regular:\n.incbin \"assets/fonts/Roboto-Regular.ttf\"\n.byte 0\n.global app_blob_font_roboto_regular_end\napp_blob_font_roboto_regular_end:\n.previous\n");
extern const uint8_t app_blob_font_roboto_regular[], app_blob_font_roboto_regular_end[];
ui_asset ui_asset_font_roboto_regular(void)
{
    ui_asset a = {app_blob_font_roboto_regular, (size_t)(app_blob_font_roboto_regular_end - app_blob_font_roboto_regular) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_font_roboto_bold\napp_blob_font_roboto_bold:\n.incbin \"assets/fonts/Roboto-Bold.ttf\"\n.byte 0\n.global app_blob_font_roboto_bold_end\napp_blob_font_roboto_bold_end:\n.previous\n");
extern const uint8_t app_blob_font_roboto_bold[], app_blob_font_roboto_bold_end[];
ui_asset ui_asset_font_roboto_bold(void)
{
    ui_asset a = {app_blob_font_roboto_bold, (size_t)(app_blob_font_roboto_bold_end - app_blob_font_roboto_bold) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_font_naskh_regular\napp_blob_font_naskh_regular:\n.incbin \"assets/fonts/NotoNaskhArabicUI-Regular.ttf\"\n.byte 0\n.global app_blob_font_naskh_regular_end\napp_blob_font_naskh_regular_end:\n.previous\n");
extern const uint8_t app_blob_font_naskh_regular[], app_blob_font_naskh_regular_end[];
ui_asset ui_asset_font_naskh_regular(void)
{
    ui_asset a = {app_blob_font_naskh_regular, (size_t)(app_blob_font_naskh_regular_end - app_blob_font_naskh_regular) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_font_naskh_bold\napp_blob_font_naskh_bold:\n.incbin \"assets/fonts/NotoNaskhArabicUI-Bold.ttf\"\n.byte 0\n.global app_blob_font_naskh_bold_end\napp_blob_font_naskh_bold_end:\n.previous\n");
extern const uint8_t app_blob_font_naskh_bold[], app_blob_font_naskh_bold_end[];
ui_asset ui_asset_font_naskh_bold(void)
{
    ui_asset a = {app_blob_font_naskh_bold, (size_t)(app_blob_font_naskh_bold_end - app_blob_font_naskh_bold) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_font_noto_emoji\napp_blob_font_noto_emoji:\n.incbin \"assets/fonts/NotoEmoji.ttf\"\n.byte 0\n.global app_blob_font_noto_emoji_end\napp_blob_font_noto_emoji_end:\n.previous\n");
extern const uint8_t app_blob_font_noto_emoji[], app_blob_font_noto_emoji_end[];
ui_asset ui_asset_font_noto_emoji(void)
{
    ui_asset a = {app_blob_font_noto_emoji, (size_t)(app_blob_font_noto_emoji_end - app_blob_font_noto_emoji) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_img_wordmark\napp_blob_img_wordmark:\n.incbin \"assets/app_logo_wordmark.png\"\n.byte 0\n.global app_blob_img_wordmark_end\napp_blob_img_wordmark_end:\n.previous\n");
extern const uint8_t app_blob_img_wordmark[], app_blob_img_wordmark_end[];
ui_asset ui_asset_img_wordmark(void)
{
    ui_asset a = {app_blob_img_wordmark, (size_t)(app_blob_img_wordmark_end - app_blob_img_wordmark) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_svg_aspect_ratio\napp_blob_svg_aspect_ratio:\n.incbin \"assets/icons/ic_player_aspect_ratio.svg\"\n.byte 0\n.global app_blob_svg_aspect_ratio_end\napp_blob_svg_aspect_ratio_end:\n.previous\n");
extern const uint8_t app_blob_svg_aspect_ratio[], app_blob_svg_aspect_ratio_end[];
ui_asset ui_asset_svg_aspect_ratio(void)
{
    ui_asset a = {app_blob_svg_aspect_ratio, (size_t)(app_blob_svg_aspect_ratio_end - app_blob_svg_aspect_ratio) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_svg_audio_filled\napp_blob_svg_audio_filled:\n.incbin \"assets/icons/ic_player_audio_filled.svg\"\n.byte 0\n.global app_blob_svg_audio_filled_end\napp_blob_svg_audio_filled_end:\n.previous\n");
extern const uint8_t app_blob_svg_audio_filled[], app_blob_svg_audio_filled_end[];
ui_asset ui_asset_svg_audio_filled(void)
{
    ui_asset a = {app_blob_svg_audio_filled, (size_t)(app_blob_svg_audio_filled_end - app_blob_svg_audio_filled) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_svg_audio_outline\napp_blob_svg_audio_outline:\n.incbin \"assets/icons/ic_player_audio_outline.svg\"\n.byte 0\n.global app_blob_svg_audio_outline_end\napp_blob_svg_audio_outline_end:\n.previous\n");
extern const uint8_t app_blob_svg_audio_outline[], app_blob_svg_audio_outline_end[];
ui_asset ui_asset_svg_audio_outline(void)
{
    ui_asset a = {app_blob_svg_audio_outline, (size_t)(app_blob_svg_audio_outline_end - app_blob_svg_audio_outline) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_svg_episodes\napp_blob_svg_episodes:\n.incbin \"assets/icons/ic_player_episodes.svg\"\n.byte 0\n.global app_blob_svg_episodes_end\napp_blob_svg_episodes_end:\n.previous\n");
extern const uint8_t app_blob_svg_episodes[], app_blob_svg_episodes_end[];
ui_asset ui_asset_svg_episodes(void)
{
    ui_asset a = {app_blob_svg_episodes, (size_t)(app_blob_svg_episodes_end - app_blob_svg_episodes) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_svg_pause\napp_blob_svg_pause:\n.incbin \"assets/icons/ic_player_pause.svg\"\n.byte 0\n.global app_blob_svg_pause_end\napp_blob_svg_pause_end:\n.previous\n");
extern const uint8_t app_blob_svg_pause[], app_blob_svg_pause_end[];
ui_asset ui_asset_svg_pause(void)
{
    ui_asset a = {app_blob_svg_pause, (size_t)(app_blob_svg_pause_end - app_blob_svg_pause) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_svg_play\napp_blob_svg_play:\n.incbin \"assets/icons/ic_player_play.svg\"\n.byte 0\n.global app_blob_svg_play_end\napp_blob_svg_play_end:\n.previous\n");
extern const uint8_t app_blob_svg_play[], app_blob_svg_play_end[];
ui_asset ui_asset_svg_play(void)
{
    ui_asset a = {app_blob_svg_play, (size_t)(app_blob_svg_play_end - app_blob_svg_play) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_svg_skip_next\napp_blob_svg_skip_next:\n.incbin \"assets/icons/ic_player_skip_next.svg\"\n.byte 0\n.global app_blob_svg_skip_next_end\napp_blob_svg_skip_next_end:\n.previous\n");
extern const uint8_t app_blob_svg_skip_next[], app_blob_svg_skip_next_end[];
ui_asset ui_asset_svg_skip_next(void)
{
    ui_asset a = {app_blob_svg_skip_next, (size_t)(app_blob_svg_skip_next_end - app_blob_svg_skip_next) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_svg_source\napp_blob_svg_source:\n.incbin \"assets/icons/ic_player_source.svg\"\n.byte 0\n.global app_blob_svg_source_end\napp_blob_svg_source_end:\n.previous\n");
extern const uint8_t app_blob_svg_source[], app_blob_svg_source_end[];
ui_asset ui_asset_svg_source(void)
{
    ui_asset a = {app_blob_svg_source, (size_t)(app_blob_svg_source_end - app_blob_svg_source) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_svg_subtitles\napp_blob_svg_subtitles:\n.incbin \"assets/icons/ic_player_subtitles.svg\"\n.byte 0\n.global app_blob_svg_subtitles_end\napp_blob_svg_subtitles_end:\n.previous\n");
extern const uint8_t app_blob_svg_subtitles[], app_blob_svg_subtitles_end[];
ui_asset ui_asset_svg_subtitles(void)
{
    ui_asset a = {app_blob_svg_subtitles, (size_t)(app_blob_svg_subtitles_end - app_blob_svg_subtitles) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_svg_check\napp_blob_svg_check:\n.incbin \"assets/icons/ic_ui_check.svg\"\n.byte 0\n.global app_blob_svg_check_end\napp_blob_svg_check_end:\n.previous\n");
extern const uint8_t app_blob_svg_check[], app_blob_svg_check_end[];
ui_asset ui_asset_svg_check(void)
{
    ui_asset a = {app_blob_svg_check, (size_t)(app_blob_svg_check_end - app_blob_svg_check) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_svg_chevron_left\napp_blob_svg_chevron_left:\n.incbin \"assets/icons/ic_ui_chevron_left.svg\"\n.byte 0\n.global app_blob_svg_chevron_left_end\napp_blob_svg_chevron_left_end:\n.previous\n");
extern const uint8_t app_blob_svg_chevron_left[], app_blob_svg_chevron_left_end[];
ui_asset ui_asset_svg_chevron_left(void)
{
    ui_asset a = {app_blob_svg_chevron_left, (size_t)(app_blob_svg_chevron_left_end - app_blob_svg_chevron_left) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_svg_chevron_right\napp_blob_svg_chevron_right:\n.incbin \"assets/icons/ic_ui_chevron_right.svg\"\n.byte 0\n.global app_blob_svg_chevron_right_end\napp_blob_svg_chevron_right_end:\n.previous\n");
extern const uint8_t app_blob_svg_chevron_right[], app_blob_svg_chevron_right_end[];
ui_asset ui_asset_svg_chevron_right(void)
{
    ui_asset a = {app_blob_svg_chevron_right, (size_t)(app_blob_svg_chevron_right_end - app_blob_svg_chevron_right) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_svg_fast_forward\napp_blob_svg_fast_forward:\n.incbin \"assets/icons/ic_ui_fast_forward.svg\"\n.byte 0\n.global app_blob_svg_fast_forward_end\napp_blob_svg_fast_forward_end:\n.previous\n");
extern const uint8_t app_blob_svg_fast_forward[], app_blob_svg_fast_forward_end[];
ui_asset ui_asset_svg_fast_forward(void)
{
    ui_asset a = {app_blob_svg_fast_forward, (size_t)(app_blob_svg_fast_forward_end - app_blob_svg_fast_forward) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_svg_fast_rewind\napp_blob_svg_fast_rewind:\n.incbin \"assets/icons/ic_ui_fast_rewind.svg\"\n.byte 0\n.global app_blob_svg_fast_rewind_end\napp_blob_svg_fast_rewind_end:\n.previous\n");
extern const uint8_t app_blob_svg_fast_rewind[], app_blob_svg_fast_rewind_end[];
ui_asset ui_asset_svg_fast_rewind(void)
{
    ui_asset a = {app_blob_svg_fast_rewind, (size_t)(app_blob_svg_fast_rewind_end - app_blob_svg_fast_rewind) - 1};
    return a;
}

__asm__(".section .rodata\n.balign 16\n.global app_blob_svg_warning\napp_blob_svg_warning:\n.incbin \"assets/icons/ic_ui_warning.svg\"\n.byte 0\n.global app_blob_svg_warning_end\napp_blob_svg_warning_end:\n.previous\n");
extern const uint8_t app_blob_svg_warning[], app_blob_svg_warning_end[];
ui_asset ui_asset_svg_warning(void)
{
    ui_asset a = {app_blob_svg_warning, (size_t)(app_blob_svg_warning_end - app_blob_svg_warning) - 1};
    return a;
}
