#!/usr/bin/env python3
"""Emit C tables of {name, offset} for chosen exports of decrypted system
libraries, for apps that cannot sceKernelDlsym them, plus one anchor string per
library (its address and text in the read-only data segment).

System library code is mapped execute-only, so the app checks the anchor string
instead: the offsets are used only if the string sits at the same offset, i.e.
it is the same library build, so other firmware fails safely.

usage: gen_export_table.py <lib.sprx> <name>... [-- <lib.sprx> <name>...] > table.h
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import ps5_dynlib  # noqa: E402


def anchor(prx):
    """First printable C string of 12+ chars in the read-only LOAD segment."""
    import re
    seg = next(p for p in prx.loads if p["flags"] == 4)
    data = prx.data[seg["offset"]:seg["offset"] + seg["filesz"]]
    m = re.search(rb"[A-Za-z][A-Za-z0-9 _%:.,()-]{11,59}\x00", data)
    text = m.group(0)[:-1].decode().replace("\\", "\\\\").replace('"', '\\"')
    return seg["vaddr"] + m.start(), text


def main():
    groups, cur = [], []
    for arg in sys.argv[1:]:
        if arg == "--":
            groups.append(cur)
            cur = []
        else:
            cur.append(arg)
    groups.append(cur)

    names = ps5_dynlib.NameDB()
    names.load_persistent()
    print("/* Generated by ps5vr/tools/gen_export_table.py - do not edit. */")
    for group in groups:
        lib, wanted = Path(group[0]), group[1:]
        prx = ps5_dynlib.Prx(lib)
        prx.resolve(names)
        by_name = {s["name"]: s for s in prx.exports() if s["name"]}
        stem = lib.name.split(".")[0]
        print(f"static const export_sig_t k{stem}Exports[] = {{")
        for name in wanted:
            s = by_name.get(name)
            if s is None:
                sys.exit(f"{lib.name}: no export named {name}")
            print(f'  {{"{name}", 0x{s["value"]:x}}},')
        print("};")
        va, text = anchor(prx)
        print(f'static const export_anchor_t k{stem}Anchor = {{0x{va:x}, "{text}"}};')


if __name__ == "__main__":
    main()
